

METADATA_FIELDS = {
    "_fields" : [
        {"name": "name", "data_type": "TEXT", "accessor": "name_postgres"},
        {"name": "data_type", "data_type": "TEXT", "accessor": "data_type"},
        {"name": "input_type", "data_type": "TEXT", "accessor": "_handle_type"},
        {"name": "table_name", "data_type": "TEXT", "accessor": "table.name_postgres"},
        # {"name": "view_name", "data_type": "TEXT", "accessor": "table.name_postgres"}, # todo
        {"name": "is_primary_key", "data_type": "BOOLEAN", "accessor": "is_primary_key"},
        {"name": "options", "data_type": "TEXT[]", "accessor": "_handle_options"},
        # {"name": "read_only", "data_type": "BOOLEAN", "accessor": "name_postgres"},
        {"name": "is_formula", "data_type": "BOOLEAN", "accessor": "is_formula"},
        {"name": "is_connection", "data_type": "BOOLEAN", "accessor": "is_connection"},
    ],
    "_views" : [
        { "name": "name", "data_type": "TEXT", "accessor": ""},
        { "name": "inputs", "data_type": "TEXT[]", "accessor": ""},
        { "name": "child_child_views", "data_type": "JSON[]", "accessor": ""},
        { "name": "_id", "data_type": "TEXT", "accessor": ""},
        { "name": "description", "data_type": "TEXT", "accessor": ""},
        { "name": "layout", "data_type": "TEXT", "accessor": ""},
        { "name": "child_scenes", "data_type": "TEXT[]", "accessor": ""},
        { "name": "type", "data_type": "TEXT", "accessor": ""},
        { "name": "rules", "data_type": "JSON", "accessor": ""},
        { "name": "options", "data_type": "JSON", "accessor": ""},
        { "name": "key", "data_type": "TEXT", "accessor": ""},
        { "name": "alert", "data_type": "TEXT", "accessor": ""},
        { "name": "limit_profile_access", "data_type": "TEXT", "accessor": ""},
        { "name": "allowed_profiles", "data_type": "TEXT[]", "accessor": ""},
        { "name": "child_views", "data_type": "TEXT[]", "accessor": ""},
        { "name": "allow_exporting", "data_type": "BOOLEAN", "accessor": ""},
        { "name": "label", "data_type": "TEXT", "accessor": ""},
        { "name": "keyword_search", "data_type": "TEXT", "accessor": ""},
        { "name": "source", "data_type": "TEXT", "accessor": ""},
        { "name": "title", "data_type": "TEXT", "accessor": ""},
        { "name": "columns", "data_type": "TEXT[]", "accessor": ""},
        { "name": "groups", "data_type": "TEXT[]", "accessor": ""},
    ],
    "_pages" : [
        {"name": "limit_profile_access", "data_type": "BOOLEAN"},
        {"name": "groups", "data_type": "TEXT[]"},
        {"name": "views", "data_type": "TEXT[]"},
        {"name": "authenticated", "data_type": "BOOLEAN"},
        {"name": "key", "data_type": "TEXT"},
        {"name": "allowed_profiles", "data_type": "TEXT[]"},
        {"name": "icon", "data_type": "TEXT"},
        {"name": "object", "data_type": "TEXT"},
        {"name": "type", "data_type": "TEXT"},
        {"name": "_views", "data_type": "TEXT[]"},
        {"name": "_id", "data_type": "TEXT"},
        {"name": "slug", "data_type": "TEXT"},
        {"name": "parent", "data_type": "TEXT"},
        {"name": "name", "data_type": "TEXT"},
    ],
}